package com.hobbyloop.feature.center


data class Region(val name: String, val subRegions: List<SubRegion>)
data class SubRegion(val name: String, val areas: List<String>)
data class SelectedRegion(val region: String, val subRegion: String, val area: String) {
    override fun toString(): String = "$region $subRegion $area"
}

val regions = listOf(
    Region(
        "서울", listOf(
            SubRegion("강남구", listOf("논현동", "개포동", "대치동", "청담동", "삼성동")),
            SubRegion("강동구", listOf("둔촌동", "천호동", "길동", "상일동")),
            SubRegion("강북구", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구", listOf("신림동", "봉천동", "낙성대동")),
            SubRegion("광진구", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구", listOf("구로동", "가리봉동", "고척동")),
            SubRegion("금천구", listOf("가산동", "독산동", "시흥동")),
            SubRegion("노원구", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구", listOf("청량리동", "회기동", "휘경동")),
            SubRegion("동작구", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        "서울1", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울2", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울3", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울4", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울5", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울6", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울7", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울8", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울9", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
    Region(
        name = "서울10", listOf(
            SubRegion("강남구1", listOf("논현동", "개포동1", "대치동", "청담동", "삼성동")),
            SubRegion("강동구1", listOf("둔촌동", "천호동1", "길동", "상일동")),
            SubRegion("강북구1", listOf("수유동", "미아동", "번동", "우이동")),
            SubRegion("강서구1", listOf("화곡동", "등촌동", "가양동", "마곡동")),
            SubRegion("관악구1", listOf("신림동", "봉천동1", "낙성대동")),
            SubRegion("광진구1", listOf("건대입구", "구의동", "자양동", "화양동")),
            SubRegion("구로구1", listOf("구로동", "가리봉동1", "고척동")),
            SubRegion("금천구1", listOf("가산동1", "독산동", "시흥동")),
            SubRegion("노원구1", listOf("상계동", "중계동", "하계동")),
            SubRegion("동대문구1", listOf("청량리동1", "회기동", "휘경동")),
            SubRegion("동작구1", listOf("사당동", "상도동", "대방동")),
            SubRegion("마포구1", listOf("합정동", "서교동", "동교동", "연남동")),
            SubRegion("서대문구", listOf("신촌동", "연희동", "홍은동")),
            SubRegion("서초구", listOf("반포동", "서초동", "잠원동")),
            SubRegion("성동구", listOf("성수동", "행당동", "왕십리동")),
            SubRegion("성북구", listOf("성북동", "돈암동", "정릉동")),
            SubRegion("송파구", listOf("잠실동", "가락동", "문정동", "방이동")),
            SubRegion("양천구", listOf("목동", "신정동", "신월동")),
            SubRegion("영등포구", listOf("여의도동", "당산동", "문래동")),
            SubRegion("용산구", listOf("이태원동", "용산동", "한남동")),
            SubRegion("은평구", listOf("응암동", "불광동", "녹번동")),
            SubRegion("종로구", listOf("삼청동", "팔판동", "청운동")),
            SubRegion("중구", listOf("명동", "을지로", "황학동")),
            SubRegion("중랑구", listOf("상봉동", "망우동", "중화동"))
        )
    ),
)